// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/saas-java": {
    params: {};
  };
  "/arquitectura-microservicios": {
    params: {};
  };
  "/integraciones-empresariales": {
    params: {};
  };
  "/migracion-sistemas-legacy": {
    params: {};
  };
  "/solucion": {
    params: {};
  };
  "/contacto": {
    params: {};
  };
  "/servicios": {
    params: {};
  };
  "/servicios/ecommerce": {
    params: {};
  };
  "/servicios/erp": {
    params: {};
  };
  "/admin": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/saas-java" | "/arquitectura-microservicios" | "/integraciones-empresariales" | "/migracion-sistemas-legacy" | "/solucion" | "/contacto" | "/servicios" | "/servicios/ecommerce" | "/servicios/erp" | "/admin";
  };
  "routes/_public.tsx": {
    id: "routes/_public";
    page: "/" | "/saas-java" | "/arquitectura-microservicios" | "/integraciones-empresariales" | "/migracion-sistemas-legacy" | "/solucion" | "/contacto" | "/servicios" | "/servicios/ecommerce" | "/servicios/erp";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/saas-java.tsx": {
    id: "routes/saas-java";
    page: "/saas-java";
  };
  "routes/arquitectura-microservicios.tsx": {
    id: "routes/arquitectura-microservicios";
    page: "/arquitectura-microservicios";
  };
  "routes/integraciones-empresariales.tsx": {
    id: "routes/integraciones-empresariales";
    page: "/integraciones-empresariales";
  };
  "routes/migracion-sistemas-legacy.tsx": {
    id: "routes/migracion-sistemas-legacy";
    page: "/migracion-sistemas-legacy";
  };
  "pages/Product.tsx": {
    id: "pages/Product";
    page: "/solucion";
  };
  "pages/Contact.tsx": {
    id: "pages/Contact";
    page: "/contacto";
  };
  "pages/Servicios.tsx": {
    id: "pages/Servicios";
    page: "/servicios";
  };
  "pages/ServicioEcommerce.tsx": {
    id: "pages/ServicioEcommerce";
    page: "/servicios/ecommerce";
  };
  "pages/ServicioERP.tsx": {
    id: "pages/ServicioERP";
    page: "/servicios/erp";
  };
  "pages/Admin.tsx": {
    id: "pages/Admin";
    page: "/admin";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_public": typeof import("./app/routes/_public.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/saas-java": typeof import("./app/routes/saas-java.tsx");
  "routes/arquitectura-microservicios": typeof import("./app/routes/arquitectura-microservicios.tsx");
  "routes/integraciones-empresariales": typeof import("./app/routes/integraciones-empresariales.tsx");
  "routes/migracion-sistemas-legacy": typeof import("./app/routes/migracion-sistemas-legacy.tsx");
  "pages/Product": typeof import("./app/pages/Product.tsx");
  "pages/Contact": typeof import("./app/pages/Contact.tsx");
  "pages/Servicios": typeof import("./app/pages/Servicios.tsx");
  "pages/ServicioEcommerce": typeof import("./app/pages/ServicioEcommerce.tsx");
  "pages/ServicioERP": typeof import("./app/pages/ServicioERP.tsx");
  "pages/Admin": typeof import("./app/pages/Admin.tsx");
};